### PR TITLE
Passthrough until the stream is ended if user returned a stream

### PR DESCRIPTION
**Pull request by Javey**
Hi. There is a problem that the next pipe will not be executed  when I returned a stream. Sometimes we need execute next pipe until the stream in `tap` function is ended. So I created a pull request.

``` javascript
gulp.task('test', function() {
    return gulp.src(paths.css)
        .pipe(doSomething())
        .pipe(tap(function() {
            return gulp.src(paths.image)
                .pipe(doSomethingElse())
        }))
        .pipe(tap(function() {
            // this will not be executed, if return a stream above
            console.log(1)
        }))
});
```

### CODE REVIEW

**Comment by Javey** [comment]
Hi @dotnetCarpenter. Why need to cache stream in `through` function. I removed it, and added a listener on `data` event. Because the filter stream pass to `through` function doesn't emit `end` event.

**Comment by dotnetCarpenter** [comment]
Hmm.. I also removed the caching in [my fork](https://github.com/dotnetCarpenter/gulp-tap/blob/master/src/tap.coffee) after leaving [a lengthy issue post about what the ramifications of caching is](https://github.com/geejs/gulp-tap/issues/6). Thanks for taking your time to change your PR. I'll merge it in.

**Comment by mloayzagahona** [comment]
@dotnetCarpenter 

Are you planning to merge this?

Thank

**Comment by dotnetCarpenter** [comment]
@mloayzagahona Unfortunately, this project seems to be abandon. I don't have any privileges to merge anything here.
That is why @Javey and I, both have forked the project and I merged-in his changes to my fork.
My fork is at:  https://github.com/Javey/gulp-tap
And @Javey is at: https://github.com/Javey/gulp-tap

Both forks are pretty much equal. I have added an example to the README and @Javey has removed the unused `event-stream` dependency.

Here is a line by line comparison: https://github.com/Javey/gulp-tap/compare/master...dotnetCarpenter:master

**Comment by dotnetCarpenter** [comment]
Merged in turn by 3ae84c3fc74c1b08f3dac1fbb46cc273632ca898

**Pull request closed without merging**
